---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: true
      changed_when: false
      when: ansible_os_family == 'Debian'
  roles:
    - ansible-role-ntp
    - ansible-role-java
    - ansible-cassandra
  post_tasks:
    - name: show seed nodes
      debug: var=cassandra_seed_resolved
